### ISSUE TITLE
undefined method `configure' for Navvy:Module

### ISSUE THREAD

**Issue by bitzesty** [jeffkreeftmeijer/navvy#1]
Trying to run a worker after following the setup guide for rails 2.3+

**Comment by jeffkreeftmeijer** [comment]
Hi,

Thanks for creating the issue, the docs were wrong. Instead of putting this in `config/initializers/navvy.rb`;

```
require 'navvy/job/active_record'
```

Do this;

```
require 'navvy'
require 'navvy/job/active_record'
```

I've updated the wiki page too -> http://wiki.github.com/jeffkreeftmeijer/navvy/installation-on-rails-2x

Thanks!
- Jeff
