### ISSUE TITLE
Backticks breaking Navvy under ActiveRecord+Postgres

### ISSUE THREAD

**Issue by adam12** [jeffkreeftmeijer/navvy#3]
The backticks used to escape column names in the active_record adapter are causing issues when using the Postgres AR adapter. Postgres uses double quotes for escaping column names (IIRC), with backticks having a different function.

The obvious solution is just to remove all the backticks from job/active_record.rb, but I wonder if there is a way to escape the column names through AR?

**Comment by fmluizao** [comment]
AR has a method called `quote_column_name` that does exactly this. It could be used in this case.

**Comment by adam12** [comment]
@fernandoluizao Thanks, not sure how I missed that one!

I've forked and pushed a fix here: adam12@087efac21b177204e937

Thoughts?

**Comment by jeffkreeftmeijer** [comment]
Great work guys, I merged your changes in and released 0.3.1 (http://rubygems.org/gems/navvy/versions/0.3.1) as a hotfix. :)

Thanks!
